//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobile_has_Violation
    {
        public int Automobile_Number_of_the_technical_passport { get; set; }
        public int Automobile_Series_of_the_technical_passport { get; set; }
        public int Violation_Code { get; set; }
        public System.DateTime Date_of_the_violation { get; set; }
    
        public virtual Automobile Automobile { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
