//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DATABASE1Entities : DbContext
    {
        public DATABASE1Entities()
            : base("name=DATABASE1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Automobile> Automobile { get; set; }
        public virtual DbSet<Automobile_has_Violation> Automobile_has_Violation { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<Violation> Violation { get; set; }
    
        public virtual ObjectResult<seaq_Result> seaq(Nullable<System.DateTime> date_of_the_violation_start, Nullable<System.DateTime> date_of_the_violation_end)
        {
            var date_of_the_violation_startParameter = date_of_the_violation_start.HasValue ?
                new ObjectParameter("Date_of_the_violation_start", date_of_the_violation_start) :
                new ObjectParameter("Date_of_the_violation_start", typeof(System.DateTime));
    
            var date_of_the_violation_endParameter = date_of_the_violation_end.HasValue ?
                new ObjectParameter("Date_of_the_violation_end", date_of_the_violation_end) :
                new ObjectParameter("Date_of_the_violation_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seaq_Result>("seaq", date_of_the_violation_startParameter, date_of_the_violation_endParameter);
        }
    
        public virtual ObjectResult<seaq2_Result> seaq2(string name_of_the_violation, string brand_of_the_automobile)
        {
            var name_of_the_violationParameter = name_of_the_violation != null ?
                new ObjectParameter("Name_of_the_violation", name_of_the_violation) :
                new ObjectParameter("Name_of_the_violation", typeof(string));
    
            var brand_of_the_automobileParameter = brand_of_the_automobile != null ?
                new ObjectParameter("Brand_of_the_automobile", brand_of_the_automobile) :
                new ObjectParameter("Brand_of_the_automobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<seaq2_Result>("seaq2", name_of_the_violationParameter, brand_of_the_automobileParameter);
        }
    }
}
